// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlimpusSN.Models;

namespace OlimpusSN.Migrations
{
    [DbContext(typeof(OlympusDbContext))]
    partial class OlympusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OlimpusSN.Models.PersonAll", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("PersonCommonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonEducationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonEmployementId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonHobbiesId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PersonCommonId");

                    b.HasIndex("PersonEducationId");

                    b.HasIndex("PersonEmployementId");

                    b.HasIndex("PersonHobbiesId");

                    b.ToTable("PersonAll");
                });

            modelBuilder.Entity("OlimpusSN.Models.PersonCommon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Birthplace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Married")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Political")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religious")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonCommon");
                });

            modelBuilder.Entity("OlimpusSN.Models.PersonEducation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodOfEducation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhereEducated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonEducation");
                });

            modelBuilder.Entity("OlimpusSN.Models.PersonEmployement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodOfEmployement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhereEmployemented")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonEmployement");
                });

            modelBuilder.Entity("OlimpusSN.Models.PersonHobbies", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavBooks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavGames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavMovies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavMusic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavTV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavWriters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobbies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInterests")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonHobbies");
                });

            modelBuilder.Entity("OlimpusSN.Models.Photografy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("OlimpusSN.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerLasnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("OlimpusSN.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonAllId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PersonAllId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OlimpusSN.Models.PersonAll", b =>
                {
                    b.HasOne("OlimpusSN.Models.PersonCommon", "PersonCommon")
                        .WithMany()
                        .HasForeignKey("PersonCommonId");

                    b.HasOne("OlimpusSN.Models.PersonEducation", "PersonEducation")
                        .WithMany()
                        .HasForeignKey("PersonEducationId");

                    b.HasOne("OlimpusSN.Models.PersonEmployement", "PersonEmployement")
                        .WithMany()
                        .HasForeignKey("PersonEmployementId");

                    b.HasOne("OlimpusSN.Models.PersonHobbies", "PersonHobbies")
                        .WithMany()
                        .HasForeignKey("PersonHobbiesId");
                });

            modelBuilder.Entity("OlimpusSN.Models.Photografy", b =>
                {
                    b.HasOne("OlimpusSN.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("OlimpusSN.Models.Post", b =>
                {
                    b.HasOne("OlimpusSN.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("OlimpusSN.Models.User", b =>
                {
                    b.HasOne("OlimpusSN.Models.PersonAll", "PersonAll")
                        .WithMany()
                        .HasForeignKey("PersonAllId");
                });
#pragma warning restore 612, 618
        }
    }
}
